workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_USER_HOME: $CI_PROJECT_DIR/.m2


.cicd_utils: &cicd_utils |
  function delete_docker_hub_image() {
    COMPONENT=$1
    JWT_TOKEN=$(curl -s -H 'Content-Type: application/json' -d '{"username": "'${DOCKER_IO_USER}'", "password": "'${DOCKER_IO_PASSWORD}'"}' https://hub.docker.com/v2/users/login/ | sed 's@.*token": "\([^"]*\)".*@\1@g')
    curl -L -X DELETE -H "Authorization: JWT $JWT_TOKEN" https://hub.docker.com/v2/repositories/podcastserver/$COMPONENT/tags/$CI_COMMIT_REF_SLUG/
  }

  function kaniko_auth_docker_hub() {
    TOKEN=$(echo -n $DOCKER_IO_USER:$DOCKER_IO_PASSWORD | base64)
    echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$TOKEN\"}}}" > /kaniko/.docker/config.json
  }

.container-scanning-with-trivy:
  image:
    name: aquasec/trivy
    entrypoint: [""]
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  cache:
    key: trivy-database
    policy: pull
    paths:
      - .trivy

.delete-docker-image:
  image: tutum/curl
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - *cicd_utils
  script:
    - delete_docker_hub_image $COMPONENT

.backend_files:
  - &changes_backend_files
    changes:
    - backend/**/*

.files_system_files:
  - &changes_files_system_files
    changes:
    - files-system/**/*

.frontend_files:
  - &changes_frontend_files
    changes:
    - frontend-angular/**/*
    - frontend-angularjs/**/*
    - ui/**/*

.not-on-master:
  - &rule-not-on-master
    if: '$CI_COMMIT_REF_NAME == "master"'
    when: never

.only-on-backend-changes:
  rules:
    - *changes_backend_files

.only-on-files-system-changes:
  rules:
    - *changes_files_system_files

.only-on-frontend-changes:
  rules:
    - *changes_frontend_files

.only-on-changes:
  rules:
    - *changes_frontend_files
    - *changes_files_system_files
    - *changes_backend_files

stages:
  - ⬇ download
  - 🧪 test
  - 👷‍ build
  - 🐳 packaging
  - 🔎 Security Analysis

⬇ container analysis db:
  stage: ⬇ download
  extends: [ .only-on-changes ]
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy --download-db-only --no-progress --cache-dir .trivy/
  cache:
    key: trivy-database
    paths:
      - .trivy
  retry: 2

⬇ backend:
  stage: ⬇ download
  extends: [ .only-on-backend-changes ]
  image: openjdk:11-slim
  script:
    - ./backend/gradlew -p backend/ downloadDependencies
  cache:
    key:
      files:
        - backend/build.gradle.kts
      prefix: "backend"
    paths:
      - .graddle/

⬇ ui-v1:
  stage: ⬇ download
  extends: [ .only-on-frontend-changes ]
  image: openjdk:8
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:install-node-and-npm frontend:npm@npm-install frontend:jspm@jspm-config frontend:jspm@jspm-install -Djspm_token=$JSPM_GITHUB_AUTH_TOKEN
  cache:
    key:
      files:
        - frontend-angularjs/npm-shrinkwrap.json
        - frontend-angularjs/www/config.js
      prefix: "ui-v1"
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/
      - .m2/

⬇ ui-v2:
  stage: ⬇ download
  extends: [ .only-on-frontend-changes ]
  image: node:11
  script:
    - yarn --cwd frontend-angular
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    paths:
      - .yarn
      - frontend-angular/node_modules/

🧪 backend:
  stage: 🧪 test
  extends: [ .only-on-backend-changes ]
  image: openjdk:11
  needs: [⬇ backend]
  services:
    - postgres:12.3-alpine
  variables:
    POSTGRES_USER: test-user
    POSTGRES_PASSWORD: LUiUwCfPwhGx1rQaUJEa7L09mdifP1Es
    POSTGRES_DB: test-db
  script:
    - ./backend/gradlew -p backend/ test
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  cache:
    key:
      files:
        - backend/build.gradle.kts
      prefix: "backend"
    policy: pull
    paths:
      - .graddle/
  retry: 2

🧪 ui-v2:
  stage: 🧪 test
  extends: [ .only-on-frontend-changes ]
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular test
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

👷 backend-base-image:
  stage: 👷‍ build
  extends: [ .only-on-backend-changes ]
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *cicd_utils
    - kaniko_auth_docker_hub
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/backend/src/main/base-image/Dockerfile --destination podcastserver/backend-base-image:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

👷 backend:
  stage: 👷‍ build
  extends: [ .only-on-backend-changes ]
  image: openjdk:11-slim
  needs: [⬇ backend]
  services:
    - postgres:12.3-alpine
  variables:
    POSTGRES_USER: build-user
    POSTGRES_PASSWORD: zSR87g1xj5TyJRZwDpyhPqkLO472QHSf
    POSTGRES_DB: build-db
  script:
    - ./backend/gradlew -p backend/ compileJava compileKotlin
  artifacts:
    paths:
      - backend/build
  cache:
    key:
      files:
        - backend/build.gradle.kts
      prefix: "backend"
    policy: pull
    paths:
      - .graddle/
  retry: 2

👷 ui-v1:
  stage: 👷‍ build
  extends: [ .only-on-frontend-changes ]
  image: openjdk:8
  needs: [⬇ ui-v1]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -f frontend-angularjs/pom.xml frontend:gulp@build-less frontend:gulp@build-app
  artifacts:
    paths:
      - frontend-angularjs/target/dist/
  cache:
    key:
      files:
        - frontend-angularjs/npm-shrinkwrap.json
        - frontend-angularjs/www/config.js
      prefix: "ui-v1"
    policy: pull
    paths:
      - frontend-angularjs/node_modules/
      - frontend-angularjs/www/jspm_packages/
      - frontend-angularjs/target/

👷 ui-v2:
  stage: 👷‍ build
  extends: [ .only-on-frontend-changes ]
  image: node:11
  needs: [⬇ ui-v2]
  script:
    - yarn --cwd frontend-angular build
  artifacts:
    paths:
      - frontend-angular/dist/
  cache:
    key:
      files:
        - frontend-angular/yarn.lock
      prefix: "ui-v2"
    policy: pull
    paths:
      - .yarn
      - frontend-angular/node_modules/

🐳 backend:
  stage: 🐳 packaging
  extends: [ .only-on-backend-changes ]
  image: openjdk:11-slim
  needs: [👷 backend, 👷 backend-base-image]
  script:
    - ./backend/gradlew -p backend/ jib
  cache:
    key:
      files:
        - backend/build.gradle.kts
      prefix: "backend"
    policy: pull
    paths:
      - .graddle/
  environment:
    name: backend/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/backend/tags
    on_stop: 🗑 backend

🗑 backend:
  stage: 🐳 packaging
  extends: [ .delete-docker-image ]
  variables:
    GIT_STRATEGY: none
  script:
    - delete_docker_hub_image backend
    - delete_docker_hub_image backend-base-image
  rules:
    - if: '$CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME == "master"'
      when: never
    - changes:
        - backend/**/*
      when: manual
      allow_failure: true
  environment:
    name: backend/$CI_COMMIT_REF_SLUG
    action: stop

🐳 init-db:
  stage: 🐳 packaging
  extends: [ .only-on-backend-changes ]
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *cicd_utils
    - kaniko_auth_docker_hub
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/database/Dockerfile --destination podcastserver/init-db:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/backend/src/main/database/Dockerfile --destination podcastserver/init-db:latest ; fi
  environment:
    name: init-db/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/init-db/tags
    on_stop: 🗑 init-db

🗑 init-db:
  stage: 🐳 packaging
  extends: [ .delete-docker-image ]
  variables:
    GIT_STRATEGY: none
    COMPONENT: init-d
  rules:
    - *rule-not-on-master
    - <<: *changes_backend_files
      when: manual
      allow_failure: true
  environment:
    name: init-db/$CI_COMMIT_REF_SLUG
    action: stop

🐳 file-system:
  stage: 🐳 packaging
  extends: [ .only-on-files-system-changes ]
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *cicd_utils
    - kaniko_auth_docker_hub
  script:
    - sh ./files-system/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/files-system/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/file-system:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/file-system:latest ; fi
  environment:
    name: file-system/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/file-system/tags
    on_stop: 🗑 file-system

🗑 file-system:
  stage: 🐳 packaging
  extends: [ .delete-docker-image ]
  variables:
    GIT_STRATEGY: none
    COMPONENT: file-system
  rules:
    - *rule-not-on-master
    - <<: *changes_files_system_files
      when: manual
      allow_failure: true
  environment:
    name: file-system/$CI_COMMIT_REF_SLUG
    action: stop

🐳 ui:
  stage: 🐳 packaging
  extends: [ .only-on-frontend-changes ]
  needs: [👷 ui-v1, 👷 ui-v2, 🧪 ui-v2]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - *cicd_utils
    - kaniko_auth_docker_hub
  script:
    - sh ./ui/compile.sh
    - export VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export PROJECT_DIR=$CI_PROJECT_DIR/ui/target/docker/
    - /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/ui:${VERSION}
    - if [ "$VERSION" == "master" ]; then /kaniko/executor --context $PROJECT_DIR --dockerfile $PROJECT_DIR/Dockerfile --destination podcastserver/ui:latest ; fi
  environment:
    name: ui/$CI_COMMIT_REF_SLUG
    url: https://cloud.docker.com/u/podcastserver/repository/docker/podcastserver/ui/tags
    on_stop: 🗑 ui

🗑 ui:
  stage: 🐳 packaging
  extends: [ .delete-docker-image ]
  variables:
    COMPONENT: ui
  rules:
    - *rule-not-on-master
    - <<: *changes_frontend_files
      when: manual
      allow_failure: true
  environment:
    name: ui/$CI_COMMIT_REF_SLUG
    action: stop

🔎 backend:
  stage: 🔎 Security Analysis
  extends: [.container-scanning-with-trivy, .only-on-backend-changes]
  needs: [⬇ container analysis db, 🐳 backend]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json podcastserver/backend:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/backend:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

🔎 init-db:
  stage: 🔎 Security Analysis
  extends: [.container-scanning-with-trivy, .only-on-backend-changes]
  needs: [⬇ container analysis db, 🐳 init-db]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json podcastserver/init-db:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/init-db:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

🔎 file-system:
  stage: 🔎 Security Analysis
  extends: [.container-scanning-with-trivy, .only-on-files-system-changes]
  needs: [⬇ container analysis db, 🐳 file-system]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json podcastserver/file-system:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/file-system:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

🔎 ui:
  stage: 🔎 Security Analysis
  extends: [.container-scanning-with-trivy, .only-on-frontend-changes]
  needs: [⬇ container analysis db, 🐳 ui]
  script:
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json podcastserver/ui:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
    - trivy --exit-code 0 --no-progress --cache-dir .trivy/ podcastserver/ui:${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}
