apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: podcastserver/backend
      context: backend
      jib:
        args:
          - -Pskaffold=true
    - image: podcastserver/ui-v1
      context: frontend-angularjs/target/
    - image: podcastserver/init-db
      docker:
        dockerfile: ./database/Dockerfile
deploy:
  kustomize:
    paths:
      - deployment/kubernetes/docker-for-desktop/
